# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  - bash: |
      set -ex

      # clean install
      npm ci
      npm run build

      mkdir -p linux
      cp -r build/* linux/

      npm run build

    displayName: Build

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: linux'
    inputs:
      PathtoPublish: linux
      ArtifactName: linux

  - bash: |
      npm run build
      npm install -g npm-cli-login
      npm-cli-login -u $(NPM_USER) -p $(NPM_PASS) -e $(NPM_EMAIL)
      npm version patch
      npm publish

    displayName: Publish

